name: kfw300 daily update

on:
  schedule:
    - cron: '0 4,5 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-kfw300:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure 06:00 Europe/Berlin
        id: berlin-time
        run: |
          HOUR=$(TZ=Europe/Berlin date +%H)
          if [ "$HOUR" != "06" ]; then
            echo "run=false" >> "$GITHUB_OUTPUT"
            echo "Skipping run at $(TZ=Europe/Berlin date)"
          else
            echo "run=true" >> "$GITHUB_OUTPUT"
            echo "Running at $(TZ=Europe/Berlin date)"
          fi

      - name: Setup Node
        if: steps.berlin-time.outputs.run == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        if: steps.berlin-time.outputs.run == 'true'
        run: npm ci

      - name: Fetch KfW 300 rates
        if: steps.berlin-time.outputs.run == 'true'
        run: npm run kfw:300

      - name: Commit and push if changed
        if: steps.berlin-time.outputs.run == 'true'
        run: |
          if git diff --quiet -- data/kfw/300.json; then
            echo "No changes in data/kfw/300.json"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/kfw/300.json
          git commit -m "chore: update KfW 300 rates"
          git push
